spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmic?useSSL=false
    username: root
    password: pmic
    hikari:
      maximum-pool-size: 5
      pool-name: pmic-connection-pool
      connection-timeout: 5000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  jpa:
    show-sql: true
    generate-ddl: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
